### ISSUE TITLE
Girls' Frontline [EN] has incorrect data

### ISSUE THREAD

**Issue by gf-db** [cicerakes/Game-Time-Master#1]
- Girls' Frontline
- EN

Girls Frontline has several things that reset daily at different times. For EN server these are:

00:00 UTC-8 - Day rollover (affects daily quests and daily login rewards)
03:00, 15:00 UTC-8 - Friend battery reset
04:00 UTC-8 - Kalina present in mail
04:00, 10:00, 16:00, 22:00 UTC-8 - Fairy order refills

**Comment by cicerakes** [comment]
Thanks for the info, the daily reset time has been changed to 00:00.
