### ISSUE TITLE
Add info for [SLIME : ISEKAI MEMORIES] (Europe)

### ISSUE THREAD

**Issue by cicerakes** [cicerakes/Game-Time-Master#124]
- **Game:** SLIME : ISEKAI MEMORIES
- **Server region/language:** Europe
- **Server timezone (location or offset):** Paris, France
- **Server daily reset time:** 5AM
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by LeSorceleurFou** [comment]
The Daily reset is 6AM i verified just now, it's not 5AM like i said previously.
