### ISSUE TITLE
Add info for [Blue Archive Global] (Global)

### ISSUE THREAD

**Issue by cicerakes** [cicerakes/Game-Time-Master#129]
- **Game:** Blue Archive Global
- **Server region/language:** Global
- **Server timezone (location or offset):** Dunno
- **Server daily reset time:** Dunno
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by cicerakes** [comment]
I can't find any info about the daily reset time.

**Comment by Zack6661** [comment]
Reset at 02:00 AM GMT +07:00 (Asia/Jakarta)

**Comment by cicerakes** [comment]
Duplicate of #131
