### ISSUE TITLE
[Feature Request] Add option to sort by games by the time until server reset

### ISSUE THREAD

**Issue by Erwinstein** [cicerakes/Game-Time-Master#140]
Good day.
As said in the title, it would be great if a kind of sorting capability is added on the website, especially since I believe there are people who juggle with something like more than 6 gacha games on a daily basis, and seeing what game to prioritize given the time until the server reset.
I kinda skimmed through the code a bit and well, it may be kinda hard to implement this, but not impossible.
I'm not really the kind of "experienced web developer" but I may try to submit a pull request if ever you are accepting (and if I ever had time to try), though I'm kinda worried that how I'll implement it will not be to your liking, if I ever tried making it.

**Comment by cicerakes** [comment]
I'm rather busy these days, and definitely open to pull requests as I likely won't have time to work on that feature.

If you manage to implement it, I'd be more than happy to review your pull request.
