### ISSUE TITLE
Add info for [IDOL M@STER CINDERELLA] (Japan)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#151]
- **Game:** IDOL M@STER CINDERELLA
- **Server region/language:** Japan
- **Server timezone (location or offset):** GMT+7
- **Server daily reset time:** 10:00 PM
- **(Optional) Does the server reset time change during the server's daylight savings?** Yes

**Comment by cicerakes** [comment]
Is this for `THE IDOLM@STER CINDERELLA GIRLS: STARLIGHT STAGE` or `THE IDOLM@STER CINDERELLA GIRLS`?  
You didn't finish the game name so I am unsure.

**Comment by cicerakes** [comment]
No response for over a month, assumed to be a duplicate of #154 and also closed due to inactivity.
