### ISSUE TITLE
Add info for [Alchemia Story] (Japan, English global server)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#152]
- **Game:** Alchemia Story
- **Server region/language:** Japan, English global server
- **Server timezone (location or offset):** JST
- **Server daily reset time:** dunno orz
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by cicerakes** [comment]
Duplicate of #158
