### ISSUE TITLE
Add info for [Sky: Children of the Light] (California, English)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#153]
- **Game:** Sky: Children of the Light
- **Server region/language:** California, English
- **Server timezone (location or offset):** PST (UTC-8)
- **Server daily reset time:** 5:00 in mine (GMT-3, summertime) and i think its 00:00 for UTC-8
- **(Optional) Does the server reset time change during the server's daylight savings?** Yes

**Comment by cicerakes** [comment]
PST and UTC-8 are actually not interchangeable, but as you mentioned the reset changes during daylight savings I will use PST.
