### ISSUE TITLE
Add info for [Blue Archive] (SEA)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#156]
- **Game:** Blue Archive
- **Server region/language:** SEA
- **Server timezone (location or offset):** UTC
- **Server daily reset time:** 4:00
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by cicerakes** [comment]
I cannot find a SEA version of the game, and Global has already been added. 

Could you provide me a link to it, if SEA is actually seperate?

**Comment by cicerakes** [comment]
No response for over a month, closed due to inactivity.
