### ISSUE TITLE
Add info for [World Flipper ] (Global)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#159]
- **Game:** World Flipper 
- **Server region/language:** Global
- **Server timezone (location or offset):** UTC+9
- **Server daily reset time:** 12:00 PST
- **(Optional) Does the server reset time change during the server's daylight savings?** Yes

**Comment by cicerakes** [comment]
Global website seems to use UTC for their news posts, so I will be using that. 

It seems they may possibly be two servers with their own timezones (EST for America and CET for Europe), but I am unsure, so let me know if I need to split Global into two servers.
