### ISSUE TITLE
Add info for [Hatsune Miku: Colorful Stage!] (EN)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#161]
- **Game:** Hatsune Miku: Colorful Stage!
- **Server region/language:** EN
- **Server timezone (location or offset):** PST
- **Server daily reset time:** 4:00 PST
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by cicerakes** [comment]
Duplicate of #157
