### ISSUE TITLE
Add info for [One Piece Treasure Cruise] (Global and Jp)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#163]
- **Game:** One Piece Treasure Cruise
- **Server region/language:** Global and Jp
- **Server timezone (location or offset):** 10:00
- **Server daily reset time:** 00:00 
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by cicerakes** [comment]
Both Global and JP servers use different timezones, PST and JST respectively. Neither seems to have anything to do with a 10 hour offset.

My research has found multiple answers for the daily reset times for both servers, none of which were midnight, so I am unsure what it actually is.

Please confirm the daily reset time for just one or both server regions (Global and/or JP), and include a location or offset with each.

**Comment by cicerakes** [comment]
No response for over a month, closed due to inactivity.
