### ISSUE TITLE
Add info for [Mythic Heroes] (Global / English)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#164]
- **Game:** Mythic Heroes
- **Server region/language:** Global / English
- **Server timezone (location or offset):** UTC 0
- **Server daily reset time:** UTC 0
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by cicerakes** [comment]
Duplicate of #162
