### ISSUE TITLE
Add info for [Punishing Grey Raven] (Asia)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#165]
- **Game:** Punishing Grey Raven
- **Server region/language:** Asia
- **Server timezone (location or offset):** UTC+8
- **Server daily reset time:** 10:00
- **(Optional) Does the server reset time change during the server's daylight savings?** Yes

**Comment by cicerakes** [comment]
Asia has already been added, as `China and Taiwan` region.

Duplicate of #61
