### ISSUE TITLE
Add info for [The Walking Dead: Survival] (English)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#166]
- **Game:** The Walking Dead: Survival
- **Server region/language:** English
- **Server timezone (location or offset):** UTC+0
- **Server daily reset time:** 8AM, GMT+8
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by cicerakes** [comment]
I cannot find a game with the exact name `The Walking Dead: Survival`, and there are many Walking Dead games with the word "survive" or similar in them. Please provide the correct game name.

**Comment by cicerakes** [comment]
No response for over a month, closed due to inactivity.
