### ISSUE TITLE
[Girls' Frontline] has incorrect data

### ISSUE THREAD

**Issue by notaadrunk** [cicerakes/Game-Time-Master#17]
- Girls' Frontline
- EN/English

-Server Reset Time, is wrong.
The real Server Reset Time is UTC-8
- My timezone is GMT-3 
- Here, in Argentina, the daily server reset time is at 05:00 AM

![image](https://user-images.githubusercontent.com/69148587/89177663-52bf4700-d562-11ea-8dc9-833168833d16.png)

![image](https://user-images.githubusercontent.com/69148587/89177688-65398080-d562-11ea-9f5b-13f11d10d284.png)

**Comment by cicerakes** [comment]
Thanks for letting me know, this is now corrected :)
