### ISSUE TITLE
Add info for [Figure Fantasy] (America)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#172]
- **Game:** Figure Fantasy
- **Server region/language:** America
- **Server timezone (location or offset):** UTC-4 (Based on the game announcement)
- **Server daily reset time:** 19.00 (in my southeast asia time)
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by cicerakes** [comment]
I'm assuming SE Asia time is UTC+7.
