### ISSUE TITLE
Add info for [Crusaders Quest] (Singapore )

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#173]
- **Game:** Crusaders Quest
- **Server region/language:** Singapore 
- **Server timezone (location or offset):** Singapore Time
- **Server daily reset time:** server's timezone
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by cicerakes** [comment]
You did not provide a daily reset time and I cannot find it online.

**Comment by cicerakes** [comment]
No response for over a month, closed due to inactivity.
