### ISSUE TITLE
Add info for [Project SEKAI Colorful Stage] (English)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#176]
- **Game:** Project SEKAI Colorful Stage
- **Server region/language:** English
- **Server timezone (location or offset):** PST
- **Server daily reset time:** 12AM PST
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by cicerakes** [comment]
This has already been added, the English version is named `HATSUNE MIKU: COLORFUL STAGE!`.

Duplicate of #157.
