### ISSUE TITLE
Add info for [Twisted Wonderland] (NA)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#177]
- **Game:** Twisted Wonderland
- **Server region/language:** NA
- **Server timezone (location or offset):** PT
- **Server daily reset time:** 17:00 GMT+8
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by cicerakes** [comment]
Duplicate of #168
