### ISSUE TITLE
Add info for Guardian Tales (Global)

### ISSUE THREAD

**Issue by blai30** [cicerakes/Game-Time-Master#18]
- **Game:** Guardian Tales
- **Server region/language:** Global/English
- **Timezone (location or offset):** UTC-8
- **Daily server reset time:** 0:00

**Comment by cicerakes** [comment]
It seems that this game has 5 servers, not just one global:
- Asia
- North America
- Europe
- Latin America
- Oceania

Are you able to confirm that all servers (or at least your own) reset at 00:00?

**Comment by blai30** [comment]
I'm sorry, I knew the game had 5 servers in the global version but I didn't realize they had different reset times. I know that the North America server resets at 1:00 AM PDT or 0:00 AM PST which should be 8:00 AM UTC
