### ISSUE TITLE
Add info for [The ants underground kingdom] (English america )

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#180]
- **Game:** The ants underground kingdom
- **Server region/language:** English america 
- **Server timezone (location or offset):** Pst
- **Server daily reset time:** 4 pm 
- **(Optional) Does the server reset time change during the server's daylight savings?** Yes

**Comment by cicerakes** [comment]
The game seems to use UTC, and a daily reset of midnight UTC seems to make more sense than 4PM PST, so I will be using that.
