### ISSUE TITLE
Add info for [Destiny Child Korea] (Korean)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#182]
- **Game:** Destiny Child Korea
- **Server region/language:** Korean
- **Server timezone (location or offset):** GMT+9 (not perfectly sure)
- **Server daily reset time:** I don't know, sorry
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by cicerakes** [comment]
I could not find the daily reset time anywhere. 

Could you provide it in your own local timezone? I can then convert that to the game/server's timezone.

**Comment by cicerakes** [comment]
No response for over a month, closed due to inactivity.
