### ISSUE TITLE
[Dragalia Lost] (Global) has incorrect data

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#185]
- **Game:** Dragalia Lost
- **Server region/language:** Global

**Correct information:** 
- **Timezone (location or offset):** UTC
- **Server daily reset time:** 6:00 UTC

(Optional) Provide an explanation and/or links/screenshots as proof: 
Currently reset is at 10pm PT, and it will be 11pm PT when daylight savings kicks in. As evidence, you can see this from the localized times in this news announcement for an event that runs through the start of daylight savings: https://dragalialost.com/en/news/detail/2901. (Note that the site localizes times to your browser, but it should be the equivalent of 6:00 UTC on both dates even though the PT time will differ for the start and end of the event.)

**Comment by cicerakes** [comment]
Since official sources such as their Twitter use PT, I will continue using this timezone.  
As for the daily reset time, I will adjust that so that it changes according to daylight savings, so it should be 10PM now (PST), and 11PM later (PDT).
