### ISSUE TITLE
Add info for [Idle huntress] (Global)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#189]
- **Game:** Idle huntress
- **Server region/language:** Global
- **Server timezone (location or offset):** UTC-5
- **Server daily reset time:** UTC-5
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by cicerakes** [comment]
I am unsure of the daily reset time and you didn't provide one, so I will be using 5AM.
