### ISSUE TITLE
Add info for [Valkyrie Connect] (Global)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#190]
- **Game:** Valkyrie Connect
- **Server region/language:** Global
- **Server timezone (location or offset):** UTC
- **Server daily reset time:** my timezone reset utc-7
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by cicerakes** [comment]
You did not provide a daily reset time, so I'm assuming it is 6 AM UTC.
