### ISSUE TITLE
Add info for [Hatsune Miku: Colorful Stage] (Global version )

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#191]
- **Game:** Hatsune Miku: Colorful Stage
- **Server region/language:** Global version 
- **Server timezone (location or offset):** PHT
- **Server daily reset time:** PHT
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by cicerakes** [comment]
Duplicate of #157
