### ISSUE TITLE
Add info for [Onmyoji] (Global/English)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#198]
- **Game:** Onmyoji
- **Server region/language:** Global/English
- **Server timezone (location or offset):** EST
- **Server daily reset time:** 12:00 AM EST
- **(Optional) Does the server reset time change during the server's daylight savings?** Yes

**Comment by cicerakes** [comment]
The game seems to use EST all year round, so there shouldn't be a daylight savings change.
