### ISSUE TITLE
Add info for [Punishing Gray Raven ] (Asia&Pacific)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#200]
- **Game:** Punishing Gray Raven 
- **Server region/language:** Asia&Pacific
- **Server timezone (location or offset):** GMT+8
- **Server daily reset time:** 15:00 GMT+8
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by cicerakes** [comment]
To my knowledge, there are only JP, CN, TW, and KR servers in Asia. The first 3 have already been added, and I don't have info for KR. 

If you want the KR server added, please mention it.

**Comment by cicerakes** [comment]
No response for over a month, closed due to inactivity.
