### ISSUE TITLE
Add info for [Seven Mortal Sins X-TASY] (EN)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#205]
- **Game:** Seven Mortal Sins X-TASY
- **Server region/language:** EN
- **Server timezone (location or offset):** PST
- **Server daily reset time:** 1 AM
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by cicerakes** [comment]
Timezone converted to UTC-5 based on research.
