### ISSUE TITLE
Add info for [Alice Closet: Anime Dress Up] (English)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#206]
- **Game:** Alice Closet: Anime Dress Up
- **Server region/language:** English
- **Server timezone (location or offset):** ET (US)
- **Server daily reset time:** 12pm ET/ 11pm CT
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by cicerakes** [comment]
Timezone converted to UTC-4 as that is what their official news uses.
