### ISSUE TITLE
Add info for [Ni no Kuni: Cross Worlds] (Global)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#208]
- **Game:** Ni no Kuni: Cross Worlds
- **Server region/language:** Global
- **Server timezone (location or offset):** NA
- **Server daily reset time:** NA
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by cicerakes** [comment]
You did not provide a daily reset time, and I am unable to find it through research.

**Comment by cicerakes** [comment]
Duplicate of #217
