### ISSUE TITLE
[Alchemy Star SEA] (SEA) has incorrect data

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#214]
- **Game:** Alchemy Star SEA
- **Server region/language:** SEA

**Correct information:** 
- **Timezone (location or offset):** Already correct
- **Server daily reset time:** Already correct

(Optional) Provide an explanation and/or links/screenshots as proof:

**Comment by cicerakes** [comment]
No info provided.
