### ISSUE TITLE
Add info for [Counter:Side Global] (Global Shop Reset)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#215]
- **Game:** Counter:Side Global
- **Server region/language:** Global Shop Reset
- **Server timezone (location or offset):** UTC+9
- **Server daily reset time:** 00:00 UTC+9
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by cicerakes** [comment]
At this time I do not plan on adding multiple timers for the same game server, and will only have one per game server for its daily reset (usually daily login rewards).
