### ISSUE TITLE
Add info for [one piece: treasure cruise] (global)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#218]
- **Game:** one piece: treasure cruise
- **Server region/language:** global
- **Server timezone (location or offset):** pst
- **Server daily reset time:** servers timezone
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by cicerakes** [comment]
No response for over a month, closed due to inactivity.
