### ISSUE TITLE
Add info for [nanatsu no taizai x-tasy] (Global/English)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#220]
- **Game:** nanatsu no taizai x-tasy
- **Server region/language:** Global/English
- **Server timezone (location or offset):** UTC-04
- **Server daily reset time:** 04:00 server's timezone
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by cicerakes** [comment]
This game has already been added as `Seven Mortal Sins X-TASY` but it seems the current timezone is incorrect, so it will be changed to UTC-04.
