### ISSUE TITLE
Add info for [Artery Gear] (Global (Europe Server))

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#222]
- **Game:** Artery Gear
- **Server region/language:** Global (Europe Server)
- **Server timezone (location or offset):** UTC+1
- **Server daily reset time:** 05:00
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by cicerakes** [comment]
Official news seems to use UTC, so I will use that.
