### ISSUE TITLE
Add info for [PUBG Mobile] (Asia)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#227]
- **Game:** PUBG Mobile
- **Server region/language:** Asia
- **Server timezone (location or offset):** Philippines
- **Server daily reset time:** Dont know
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by cicerakes** [comment]
I can't find info on server times for different servers, so I am just adding it as 00:00 global.
