### ISSUE TITLE
Add info for Princess Connect (Global Soft Launch)

### ISSUE THREAD

**Issue by benmanuel12** [cicerakes/Game-Time-Master#23]
- **Game: Princess Connect (Global Soft Launch)**
- **Server region/language:** App uses english, not sure what regions its planned to release on when it leaves soft launch
- **Server timezone (location or offset):** UTC
- **Daily server reset time:** 1pm
- **(Optional) Does the server reset time change during the server's daylight savings?** For example, if the reset time is 05:00 during PST and also 05:00 during PDT, you would answer `No`. If the reset time changed to 06:00 during PDT, you would answer `Yes`. This question only applies if the server itself changes timezones during daylight savings. **If unsure, skip this question.**

I'm not sure if the time I provided is accurate, feel free to double check

**Comment by cicerakes** [comment]
I've set the region as EN since that seems to be what they use on official social media. 

As for the times, I can't personally check since the soft launch hasn't started in my region, and there's not much info on Google. So for now I'll go with what you've provided unless someone else corrects it.

**Comment by benmanuel12** [comment]
So as i write this, its about 9 pm Friday. Princess Connect tells me I have 16 hrs remaining to do my dailies, which would mean 1pm GMT tomorrow.
What I said earlier appears to be correct.
Do change it if I'm wrong but my evidence taken from the game is at least not based on a guess.

**Comment by cicerakes** [comment]
I can now also confirm it is correct, so no worries there.

**Comment by benmanuel12** [comment]
Great. I'm very new to Github collaboration stuff
