### ISSUE TITLE
[My Hero Academia: The Strongest Hero] (EN) is affected by daylight savings

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#230]
- **Game:** My Hero Academia: The Strongest Hero
- **Server region/language:** EN

- **First server daily reset time:** 05:00 PDT
- **Second server daily reset time:** 06:00 PDT

**Comment by cicerakes** [comment]
Having a second reset time of 06:00 PDT means the game would reset at 05:00 PST, which is already does so currently.  

If the game instead has an incorrect timezone and is swapping to PST at the wrong time, please leave a comment with more info or create a new issue.
