### ISSUE TITLE
[Sky: Children of the Light] (Global) is affected by daylight savings

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#232]
- **Game:** Sky: Children of the Light
- **Server region/language:** Global

- **First server daily reset time:** 01:00 PDT
- **Second server daily reset time:** 00:00 PDT

**Comment by cicerakes** [comment]
I'm assuming you meant 00:00 PST for the second reset time.

**Comment by cicerakes** [comment]
As mentioned in #153, this game server has already been adjusted for daylight savings.  

If you instead believe this adjustment should be removed, or the daily reset time is incorrect, please leave a comment or create a new issue.
