### ISSUE TITLE
Add info for [NU: Carnival] (EN )

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#233]
- **Game:** NU: Carnival
- **Server region/language:** EN 
- **Server timezone (location or offset):** unsure
- **Server daily reset time:** GMT+8, 5:00 AM
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by cicerakes** [comment]
Duplicate of #196
