### ISSUE TITLE
Add info for [One punch man the strongest] (Sea region/ english language)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#236]
- **Game:** One punch man the strongest
- **Server region/language:** Sea region/ english language
- **Server timezone (location or offset):** GMT+8
- **Server daily reset time:** GMT+8
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by cicerakes** [comment]
Please provide a **daily reset time** as I cannot find any info on it.  

GMT+8 is a **timezone**, not a reset time.

**Comment by cicerakes** [comment]
No response for a month, closed due to inactivity.
