### ISSUE TITLE
Add info for [Noah's Heart] (S1 - Avant Garde)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#237]
- **Game:** Noah's Heart
- **Server region/language:** S1 - Avant Garde
- **Server timezone (location or offset):** GMT-5
- **Server daily reset time:** 00:00
- **(Optional) Does the server reset time change during the server's daylight savings?** No

**Comment by cicerakes** [comment]
I don't know what region "S1 - Avant Garde" is from, so I'm assuming Global.
