### ISSUE TITLE
Add info for [Grimlight] (Global)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#240]
- **Game:** Grimlight
- **Server region/language:** Global
- **Server timezone (location or offset):** UTC+1
- **Server daily reset time:** 5am
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by cicerakes** [comment]
Daily reset time converted to 4AM UTC, as UTC is what official sources use.
