### ISSUE TITLE
Add info for [Octopath Traveler: Champions of the Continent] (Global/English)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#241]
- **Game:** Octopath Traveler: Champions of the Continent
- **Server region/language:** Global/English
- **Server timezone (location or offset):** Japan
- **Server daily reset time:** 0900 UTC
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by cicerakes** [comment]
Added as UTC as official news uses that and not JST.
