### ISSUE TITLE
Add info for [Last Origin] (BOTH JP & Korea)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#243]
- **Game:** Last Origin
- **Server region/language:** BOTH JP & Korea
- **Server timezone (location or offset):** Tokyo,Japan &KST
- **Server daily reset time:** I Think it around 9.00 utc+7
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by cicerakes** [comment]
Wiki states 9AM KST for Korea. 

I was unable to find anything about Japan server, so I will not add it right now.
