### ISSUE TITLE
Add info for [Dragon Ball Legends] (Global/EN)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#245]
- **Game:** Dragon Ball Legends
- **Server region/language:** Global/EN
- **Server timezone (location or offset):** UTC
- **Server daily reset time:** 06:00 AM UTC
- **(Optional) Does the server reset time change during the server's daylight savings?** Yes

**Comment by cicerakes** [comment]
UTC cannot be affected by daylight savings.
