### ISSUE TITLE
Add info for [RED: Pride of Eden] (JP)

### ISSUE THREAD

**Issue by zxrqwertc** [cicerakes/Game-Time-Master#25]
- **Game:RED: Pride of Eden**
- **Server region/language:JP**
- **Server timezone (location or offset):UTC+9**
- **Daily server reset time:04:00 am UTC+9**
- **(Optional) Does the server reset time change during the server's daylight savings?** For example, if the reset time is 05:00 during PST and also 05:00 during PDT, you would answer `No`. If the reset time changed to 06:00 during PDT, you would answer `Yes`. This question only applies if the server itself changes timezones during daylight savings. **If unsure, skip this question.**

**Comment by cicerakes** [comment]
I've added it as JST since it is the same as UTC+9 and the game is in Japan.
