### ISSUE TITLE
Add info for [Shall We Date?: Obey Me!] (Global/English)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#258]
- **Game:** Shall We Date?: Obey Me!
- **Server region/language:** Global/English
- **Server timezone (location or offset):** JST
- **Server daily reset time:** 00:00 (JST)/23:00 (GMT+8)
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by cicerakes** [comment]
Duplicate of #255
