### ISSUE TITLE
Add info for [Aether Gazer] (Server Chinese)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#259]
- **Game:** Aether Gazer
- **Server region/language:** Server Chinese
- **Server timezone (location or offset):** GMT+8
- **Server daily reset time:** UTC+7
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by cicerakes** [comment]
Please provide a **server daily reset time** and not just an offset (e.g. 9AM), as I could not find info for it.

**Comment by cicerakes** [comment]
No response for over a month, closed due to inactivity.
