### ISSUE TITLE
Add info for [Echocalypse] (SEA/Indonesia)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#260]
- **Game:** Echocalypse
- **Server region/language:** SEA/Indonesia
- **Server timezone (location or offset):** UTC+7
- **Server daily reset time:** UTC+7
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by cicerakes** [comment]
Please provide a **server daily reset time** and not just an offset (e.g. 9AM), as I could not find info for it.

**Comment by cicerakes** [comment]
Duplicate of #270
