### ISSUE TITLE
Add info for [Girls' Connect IDLE RPG] (Philippines)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#262]
- **Game:** Girls' Connect IDLE RPG
- **Server region/language:** Philippines
- **Server timezone (location or offset):** GMT+8
- **Server daily reset time:** 12
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by cicerakes** [comment]
Please clarify whether the server daily reset time is 12 PM or 12 AM.

**Comment by cicerakes** [comment]
No response for a month, closed due to inactivity.
