### ISSUE TITLE
Add info for [Disgaea RPG] (English)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#263]
- **Game:** Disgaea RPG
- **Server region/language:** English
- **Server timezone (location or offset):** GMT+2
- **Server daily reset time:** GMT+2 - 6AM
- **(Optional) Does the server reset time change during the server's daylight savings?** No

**Comment by cicerakes** [comment]
Official site uses UTC-4, so your reset time will be converted to 00:00.
