### ISSUE TITLE
Add info for [tensura king of monster] (indonesia)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#272]
- **Game:** tensura king of monster
- **Server region/language:** indonesia
- **Server timezone (location or offset):** japan
- **Server daily reset time:** when reset?
- **(Optional) Does the server reset time change during the server's daylight savings?** Yes

**Comment by cicerakes** [comment]
I was able to find that the game uses UTC+8, but unable to find a daily reset time. 

Please provide a daily reset time.

**Comment by cicerakes** [comment]
No response for over a month, closed due to inactivity.
