### ISSUE TITLE
Add info for [Guardian Tales] (America/Toronto)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#273]
- **Game:** Guardian Tales
- **Server region/language:** America/Toronto
- **Server timezone (location or offset):** GMT -04:00
- **Server daily reset time:** GMT -04:00
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by cicerakes** [comment]
I am unable to find evidence of a Canada server for this game. 

[Official FAQ has a list of servers available,](https://guardiantales.zendesk.com/hc/en-us/articles/360009804038-Arena-Co-op-opening-times) all of which have already been added.
