### ISSUE TITLE
Add info for [SoulWorker] (Global, English/Japanese audio)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#277]
- **Game:** SoulWorker
- **Server region/language:** Global, English/Japanese audio
- **Server timezone (location or offset):** PDT/PST 18:00
- **Server daily reset time:** GMT 01:00
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by cicerakes** [comment]
There are a few games that use the name "SoulWorker", but I am assuming you're referring to the MMO available on PC.

As official news uses GMT, I will be using that instead of PST/PDT.
