### ISSUE TITLE
Add info for [SAO ARS] (Global)

### ISSUE THREAD

**Issue by Mujina7569** [cicerakes/Game-Time-Master#28]
- **Game:** SWORD ART ONLINE Alicization Rising Steel
- **Server region/language:** Not sure/EN
- **Server timezone (location or offset):** UTC
- **Daily server reset time:** 03:00
- **(Optional) Does the server reset time change during the server's daylight savings?** Not sure maybe no

Source: https://www.facebook.com/SAO.risingsteel

**Comment by cicerakes** [comment]
I've gone with "Global" as the region, since it seems that multiple languages use the same APK.
