### ISSUE TITLE
Add info for [NIKKE: GODDESS OF VICTORY ] (Global)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#280]
- **Game:** NIKKE: GODDESS OF VICTORY 
- **Server region/language:** Global
- **Server timezone (location or offset):** GMT+8
- **Server daily reset time:** 12 am
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by cicerakes** [comment]
Duplicate of #288
