### ISSUE TITLE
Add info for [Goddess of Victory: Nikke] (Global )

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#281]
- **Game:** Goddess of Victory: Nikke
- **Server region/language:** Global 
- **Server timezone (location or offset):** GMT
- **Server daily reset time:** Unsure
- **(Optional) Does the server reset time change during the server's daylight savings?** Yes

**Comment by cicerakes** [comment]
Duplicate of #288
