### ISSUE TITLE
Add info for [Punishing gray raven] (Asia Pacific/english)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#290]
- **Game:** Punishing gray raven
- **Server region/language:** Asia Pacific/english
- **Server timezone (location or offset):** WIB
- **Server daily reset time:** Nothing
- **(Optional) Does the server reset time change during the server's daylight savings?** No

**Comment by cicerakes** [comment]
Duplicate of #200

**Comment by cicerakes** [comment]
Asia-Pacific server goes under Global, which has already been added.
