### ISSUE TITLE
Add info for [Goddess of Victory: Nikke] (NA)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#292]
- **Game:** Goddess of Victory: Nikke
- **Server region/language:** NA
- **Server timezone (location or offset):** UTC
- **Server daily reset time:** 20:00 UTC
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by cicerakes** [comment]
Duplicate of #301
