### ISSUE TITLE
Add info for [Shadowverse] (Global)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#294]
- **Game:** Shadowverse
- **Server region/language:** Global
- **Server timezone (location or offset):** PT UTC−07:00
- **Server daily reset time:** 1 p.m. PDT (not sure sorry)
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by Mujina7569** [comment]
Update Info

- Server daily reset time: 12:00 noon.,  (PT)
- (Optional) Does the server reset time change during the server's daylight savings? No
