### ISSUE TITLE
Add info for [Neural Cloud] (EN)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#296]
- **Game:** Neural Cloud
- **Server region/language:** EN
- **Server timezone (location or offset):** can't find it sorry
- **Server daily reset time:** 19:00 GMT+7
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by cicerakes** [comment]
Duplicate of #299
