### ISSUE TITLE
Add info for [Girls' Frontline: Project Neural Cloud] (EN)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#297]
- **Game:** Girls' Frontline: Project Neural Cloud
- **Server region/language:** EN
- **Server timezone (location or offset):** We think it's UTC -8
- **Server daily reset time:** 7 A.M. CST
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by cicerakes** [comment]
Duplicate of #299
