### ISSUE TITLE
Add info for [Neural Cloud] (Global)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#300]
- **Game:** Neural Cloud
- **Server region/language:** Global
- **Server timezone (location or offset):** GMT+7
- **Server daily reset time:** 11.00PM (GMT+7)
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by cicerakes** [comment]
Duplicate of #299
