### ISSUE TITLE
Add info for [Girls' frontline project neural cloud] (GLOBAL/EN)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#303]
- **Game:** Girls' frontline project neural cloud
- **Server region/language:** GLOBAL/EN
- **Server timezone (location or offset):** GMT +8
- **Server daily reset time:** 21:00 PHST
- **(Optional) Does the server reset time change during the server's daylight savings?** No

**Comment by cicerakes** [comment]
Duplicate of #299
