### ISSUE TITLE
Add info for [Girls Frontline: Neural Cloud-EN] (Global/Asia)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#306]
- **Game:** Girls Frontline: Neural Cloud-EN
- **Server region/language:** Global/Asia
- **Server timezone (location or offset):** UTC+08:00, Singapore
- **Server daily reset time:** 20:00
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by cicerakes** [comment]
Duplicate of #299
