### ISSUE TITLE
Add info for [Neural Cloud girls Frontline ] (Global/English)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#307]
- **Game:** Neural Cloud girls Frontline 
- **Server region/language:** Global/English
- **Server timezone (location or offset):** 10:00 PM JST/ 22:00 JST
- **Server daily reset time:** 10:00 PM JST / 22:00 JST
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by cicerakes** [comment]
Duplicate of #299
