### ISSUE TITLE
Add info for [Love Live! School Idol Festival ALL STARS] (Global)

### ISSUE THREAD

**Issue by mogalord** [cicerakes/Game-Time-Master#31]
- **Game:** Love Live School idol Festival All Stars
- **Server region/language:** NA (The NA server is soon merging with the JP server)
- **Server timezone (location or offset):** JST
- **Daily server reset time:** 4am JST
- **(Optional) Does the server reset time change during the server's daylight savings?** For example, if the reset time is 05:00 during PST and also 05:00 during PDT, you would answer `No`. If the reset time changed to 06:00 during PDT, you would answer `Yes`. This question only applies if the server itself changes timezones during daylight savings. **If unsure, skip this question.**

**Comment by cicerakes** [comment]
I've set the region as "Global" since that's what they use. 

Regarding the server merge, that seems to only apply to the non-ALL STARS version of the game.
