### ISSUE TITLE
Add info for [Heaven Burns Red ] (Japanese )

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#310]
- **Game:** Heaven Burns Red 
- **Server region/language:** Japanese 
- **Server timezone (location or offset):** Tokyo, Japan
- **Server daily reset time:** 05:00
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by BeaxV** [comment]
Server daily reset time is actually an hour earlier at 04:00, and not at 05:00
