### ISSUE TITLE
Add info for [Evertale] (Asia)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#313]
- **Game:** Evertale
- **Server region/language:** Asia
- **Server timezone (location or offset):** I can't math, their Discord server just provide server daily reset time
- **Server daily reset time:** 5 PM PST
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by ShiroKazane** [comment]
Server timezone is UTC+9
