### ISSUE TITLE
Add info for [Exos_Heroes] (GLOBAL)

### ISSUE THREAD

**Issue by Sam-Jnr** [cicerakes/Game-Time-Master#32]
- **Game:** Exos Heroes
- **Server region/language:** Global, English
- **Server timezone (location or offset):** Europe/London
- **Daily server reset time:** 20:00 Europe/London — GMT +00:00
- **(Optional) Does the server reset time change during the server's daylight savings?** For example, if the reset time is 05:00 during PST and also 05:00 during PDT, you would answer `No`. If the reset time changed to 06:00 during PDT, you would answer `Yes`. This question only applies if the server itself changes timezones during daylight savings. **If unsure, skip this question.**

**Comment by cicerakes** [comment]
I've used UTC instead of GMT since that's what they use for their official Facebook announcements. Feel free to correct me if it's actually GMT in-game.
