### ISSUE TITLE
Add info for [Eversoul] (NA/Global)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#320]
- **Game:** Eversoul
- **Server region/language:** NA/Global
- **Server timezone (location or offset):** 00:00 UTC
- **Server daily reset time:** 7:00 pm EST
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by cicerakes** [comment]
Duplicate of #314
