### ISSUE TITLE
[Goddess of Victory: Nikke] (NA) has incorrect data

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#322]
- **Game:** Goddess of Victory: Nikke
- **Server region/language:** NA

**Correct information:** 
- **Timezone (location or offset):** Already correct
- **Server daily reset time:** Already correct

(Optional) Provide an explanation and/or links/screenshots as proof: 
It is counting UP from reset not counting down To reset

**Comment by cicerakes** [comment]
Duplicate of #50
