### ISSUE TITLE
Add info for [Destiny 2] (Global)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#326]
- **Game:** Destiny 2
- **Server region/language:** Global
- **Server timezone (location or offset):** Bellevue, Washington
- **Server daily reset time:** UTC -8
- **(Optional) Does the server reset time change during the server's daylight savings?** No

**Comment by cicerakes** [comment]
Using the times from [the official help docs](https://help.bungie.net/hc/en-us/articles/360049199911-Destiny-2-Ritual-Reset-Guide) instead.
