### ISSUE TITLE
Add info for [Evertale & Destiny Girl & Girl's Connect & Eversoul] (SEA/EN)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#327]
- **Game:** Evertale & Destiny Girl & Girl's Connect & Eversoul
- **Server region/language:** SEA/EN
- **Server timezone (location or offset):** GMT+8
- **Server daily reset time:** 4.00 am GMT+8
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by cicerakes** [comment]
Please only submit requests for one game at a time.
