### ISSUE TITLE
Add info for [Limbus Company] (EN/Global)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#331]
- **Game:** Limbus Company
- **Server region/language:** EN/Global
- **Server timezone (location or offset):** Korea, UTC+9
- **Server daily reset time:** 11:00 PM UTC +3
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by cicerakes** [comment]
Duplicate of #345
