### ISSUE TITLE
Add info for [The eminence in shadow RPG] (Global)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#333]
- **Game:** The eminence in shadow RPG
- **Server region/language:** Global
- **Server timezone (location or offset):** Sorry I don't remember
- **Server daily reset time:** 19:00 UTC
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by cicerakes** [comment]
Duplicate of #304
