### ISSUE TITLE
Add info for [Higan: Eruthyll ] (NA)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#350]
- **Game:** Higan: Eruthyll 
- **Server region/language:** NA
- **Server timezone (location or offset):** GMT-8
- **Server daily reset time:** 6AM GMT-8
- **(Optional) Does the server reset time change during the server's daylight savings?** Yes

**Comment by albo44** [comment]
It actually resets at 5 am gmt-8
