### ISSUE TITLE
Add info for [Goddess of Victory: Nikke] (North America)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#364]
- **Game:** Goddess of Victory: Nikke
- **Server region/language:** North America
- **Server timezone (location or offset):** UNSURE
- **Server daily reset time:** 6am UTC+10
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by cicerakes** [comment]
Duplicate of #301
