### ISSUE TITLE
Add info for [Life Makeover] (Global)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#365]
- **Game:** Life Makeover
- **Server region/language:** Global
- **Server timezone (location or offset):** UTC+0
- **Server daily reset time:** 5 am UTC+0
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by cicerakes** [comment]
Added in 3c4281265c97f0784e278294a5ad43615192e9e2
