### ISSUE TITLE
Add info for [Aether Gazer] (Global / English)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#374]
- **Game:** Aether Gazer
- **Server region/language:** Global / English
- **Server timezone (location or offset):** UTC - 7
- **Server daily reset time:** 8PM PHT (UTC +8)
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by cicerakes** [comment]
Duplicate of #368
