### ISSUE TITLE
Add info for [Outerplane] (Asia / English)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#375]
- **Game:** Outerplane
- **Server region/language:** Asia / English
- **Server timezone (location or offset):** UTC 
- **Server daily reset time:** 8AM PHT (UTC + 8)
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by cicerakes** [comment]
Duplicate of #377
