### ISSUE TITLE
Google Forms submission form appears to be broken

### ISSUE THREAD

**Issue by dburr** [cicerakes/Game-Time-Master#385]
I used the Google form linked off of the github.io site to submit two game requests recently, but they have not yet appeared here in the github issues. One of them was a dupe of an already-listed game (completely my fault, I admit it) so when it didn't appear I thought that the script had some form of automatic de-duping. However today I submitted a new game (Snowbreak: Containment Zone) which I know isn't yet in the database, however it has been over an hour and that submission hasn't yet appeared in the github issues. The last github issue created via submission form appears to be dated Jun 5, so it would seem that the form has been broken for almost 2 months now.

**Comment by cicerakes** [comment]
Thanks for letting me know, this should now be fixed. 

I've manually added the missing submissions.
