### ISSUE TITLE
Add info for [Snowbreak: Containment Zone] (All)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#386]
- **Game:** Snowbreak: Containment Zone
- **Server region/language:** All
- **Server timezone (location or offset):** UTC+8
- **Server daily reset time:** 05:00
- **(Optional) Does the server reset time change during the server's daylight savings?** No

**Comment by cicerakes** [comment]
Duplicate of #391
