### ISSUE TITLE
Add info for [Snowbreak: Containment Zone] (Global)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#391]
- **Game:** Snowbreak: Containment Zone
- **Server region/language:** Global
- **Server timezone (location or offset):** UTC+8
- **Server daily reset time:** UTC+8 4am
- **(Optional) Does the server reset time change during the server's daylight savings?** No

**Comment by cicerakes** [comment]
I'm going to assume all the in-game servers (Asia, Europe, etc.) use the same reset time.
