### ISSUE TITLE
[Love nikki Dress up queen] (Global server) has incorrect data

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#393]
- **Game:** Love nikki Dress up queen
- **Server region/language:** Global server

**Correct information:** 
- **Timezone (location or offset):** Already correct
- **Server daily reset time:** The reset time for this game is in game time 05:00 and acording to the website in my time zone it was 12:00 but the game time is only 03:47 right not and my time is 13:47 game reset happenes in 1 hour at 15:00 in my timezone Oslp norway time europe

(Optional) Provide an explanation and/or links/screenshots as proof: 
i have screen shot but there is no where to add it

**Comment by cicerakes** [comment]
I have corrected the server's timezone to UTC-8. 

Feel free to let me know if there are still issues with it.
