### ISSUE TITLE
Add info for [Snowbreak: Containtment Zone] (Japan)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#398]
- **Game:** Snowbreak: Containtment Zone
- **Server region/language:** Japan
- **Server timezone (location or offset):** GMT+8
- **Server daily reset time:** 8 or 9 pm BST
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by cicerakes** [comment]
Duplicate of #391
