### ISSUE TITLE
Add info for [Honkai Star Rail] (Asia)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#400]
- **Game:** Honkai Star Rail
- **Server region/language:** Asia
- **Server timezone (location or offset):** GMT+8
- **Server daily reset time:** 4:00
- **(Optional) Does the server reset time change during the server's daylight savings?** No

**Comment by AVSGamer** [comment]
Sorry, this one's my request and so are the Summoner's War: Chronicles, Pokemon TCG Live and Crypto Ball Z, etc..
This one didn't show up when I searched it but it eventually did, guess you might want to trim the Search Box's entry for whitespaces. Awesome project! Thanks! No longer have to keep track of my games with a notepad. LOL

**Comment by AVSGamer** [comment]
Trim Search Box entry's trailing and starting whitespaces and use SQL comparator LIKE or some regex that would show all entries that contains the entry.

**Comment by cicerakes** [comment]
Thanks for letting me know about the whitespace issue.
