### ISSUE TITLE
Add info for [Summoner's War: Chronicles] (Asia)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#402]
- **Game:** Summoner's War: Chronicles
- **Server region/language:** Asia
- **Server timezone (location or offset):** GMT+8
- **Server daily reset time:** 1:00
- **(Optional) Does the server reset time change during the server's daylight savings?** No

**Comment by cicerakes** [comment]
Adjusted to 0:00 GMT+7 based on time zones listed in [recent patch notes](https://community.summonerswar.com/chronicles/eng-us/board/16/59523?MainGotoPage=11).
