### ISSUE TITLE
Add info for [OuterPlane] (GLOBAL/English)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#407]
- **Game:** OuterPlane
- **Server region/language:** GLOBAL/English
- **Server timezone (location or offset):** I don't know I missed it
- **Server daily reset time:** I don't know I missed it
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by cicerakes** [comment]
Duplicate of #377
