### ISSUE TITLE
Add info for [Snowbreak: Containment Zone] (Southeast Asia)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#408]
- **Game:** Snowbreak: Containment Zone
- **Server region/language:** Southeast Asia
- **Server timezone (location or offset):** idk
- **Server daily reset time:** idk
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by cicerakes** [comment]
Duplicate of #391
