### ISSUE TITLE
Add info for [Final Fantasy VII: Ever Crisis] (Global)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#412]
- **Game:** Final Fantasy VII: Ever Crisis
- **Server region/language:** Global
- **Server timezone (location or offset):** JST (Assuming)
- **Server daily reset time:** 5:00am JST (4:00pm EDT)
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by cicerakes** [comment]
Converted to PT based on official news posts.
