### ISSUE TITLE
Add info for [Yugioh duel links ] (Global)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#420]
- **Game:** Yugioh duel links 
- **Server region/language:** Global
- **Server timezone (location or offset):** London+1
- **Server daily reset time:** 7pm London time
- **(Optional) Does the server reset time change during the server's daylight savings?** No

**Comment by cicerakes** [comment]
Going to use 5AM JST as the reset time.
