### ISSUE TITLE
Add info for [Project SEKAI COLORFUL STAGE! feat. Hatsune Miku] (EN)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#425]
- **Game:** Project SEKAI COLORFUL STAGE! feat. Hatsune Miku
- **Server region/language:** EN
- **Server timezone (location or offset):** PST
- **Server daily reset time:** 4am PST
- **(Optional) Does the server reset time change during the server's daylight savings?** No

**Comment by cicerakes** [comment]
Duplicate of #157
