### ISSUE TITLE
Add info for [life makeover] (global/english)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#427]
- **Game:** life makeover
- **Server region/language:** global/english
- **Server timezone (location or offset):** unknown/unsure
- **Server daily reset time:** unknown/unsure
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by cicerakes** [comment]
Duplicate of #365

**Comment by cicerakes** [comment]
Added in 3c4281265c97f0784e278294a5ad43615192e9e2
