### ISSUE TITLE
Add info for [What in Hell is Bad] (Global)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#429]
- **Game:** What in Hell is Bad
- **Server region/language:** Global
- **Server timezone (location or offset):** KST
- **Server daily reset time:** 11 PM GMT+8
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by cicerakes** [comment]
Duplicate of #426
