### ISSUE TITLE
Add info for [Tower of God: New World] (Global/NA)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#431]
- **Game:** Tower of God: New World
- **Server region/language:** Global/NA
- **Server timezone (location or offset):** UTC-8
- **Server daily reset time:** 5PM PST 
- **(Optional) Does the server reset time change during the server's daylight savings?** Yes

**Comment by cicerakes** [comment]
Will be using 4 PM based on the [login reward time from this event](https://forum.netmarble.com/towerofgod_en/view/48/2136).  
If this event actually uses a different reset time from the standard daily reset, feel free to correct me.
