### ISSUE TITLE
Add info for [Reverse 1999] (Global/NA)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#432]
- **Game:** Reverse 1999
- **Server region/language:** Global/NA
- **Server timezone (location or offset):** UTC-5
- **Server daily reset time:** 12:00 UTC-0
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by cicerakes** [comment]
Duplicate of #435
