### ISSUE TITLE
Add info for [World dai star: yume no stellarium] (Japan server)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#496]
- **Game:** World dai star: yume no stellarium
- **Server region/language:** Japan server
- **Server timezone (location or offset):** Tokyo, Japan (i think)
- **Server daily reset time:** 5:00 am I believe
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by cicerakes** [comment]
Duplicate of #409
