### ISSUE TITLE
Add info for [Final Fantasy Vii Ever Crisis] (Global)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#528]
- **Game:** Final Fantasy Vii Ever Crisis
- **Server region/language:** Global
- **Server timezone (location or offset):** jst
- **Server daily reset time:** 0600 jst
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by cicerakes** [comment]
Duplicate of #412
