### ISSUE TITLE
Add info for [Final Fantasy VII: Ever Crisis] (Global/English)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#556]
- **Game:** Final Fantasy VII: Ever Crisis
- **Server region/language:** Global/English
- **Server timezone (location or offset):** GMT-4
- **Server daily reset time:** 04:00 PM GMT-4
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by cicerakes** [comment]
Duplicate of #412
