### ISSUE TITLE
Add info for [Sword of Convallaria] (Global, Taiwan)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#562]
- **Game:** Sword of Convallaria
- **Server region/language:** Global, Taiwan
- **Server timezone (location or offset):** Unsure
- **Server daily reset time:** 9:30 AM Indian Standard Time
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by cicerakes** [comment]
Duplicate of #551
