### ISSUE TITLE
Add info for [Sword of Convallaria] (Global)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#598]
- **Game:** Sword of Convallaria
- **Server region/language:** Global
- **Server timezone (location or offset):** Canada, Vancouver 
- **Server daily reset time:** 8:00 PM
- **(Optional) Does the server reset time change during the server's daylight savings?** Yes

**Comment by cicerakes** [comment]
Duplicate of #551
