### ISSUE TITLE
Add info for [Girl's Frontline 2] (Global/EN)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#602]
- **Game:** Girl's Frontline 2
- **Server region/language:** Global/EN
- **Server timezone (location or offset):** -
- **Server daily reset time:** 11:18 PM
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by cicerakes** [comment]
Duplicate of #591
